<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Mono-friendly classic profile -->
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <!-- Optional: emit pdb for nicer stack traces -->
    <DebugType>portable</DebugType>

    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Reference the dynamically built Engine.dll -->
    <Reference Include="Engine">
      <HintPath>..\..\Engine\bin\Release\net8.0\Engine.dll</HintPath>
      <Private>false</Private> 
    </Reference>
  </ItemGroup>
</Project>
